title: "Yao (Emma) Chen"
author: "Yao (Emma) Chen"
description: "Indiana University School of Medicine"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_social: true 
show_excerpts: false        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: true             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {url: "/", icon: home, title: "Home"}
  # - {file: "README.md", title: "About me", icon: address-card}
  - {title: "Blog", file: "blog.md"} 
  - {title: "CV", url: "https://drive.google.com/file/d/1Z3PBpp69J2SJy1L2I3jPYJG5pnKl-uUX/view?usp=sharing"}
  - {title: "Publications", url: "https://www.researchgate.net/profile/Yao-Chen-98"}
  - {title: Mail, icon: envelope, url: "mailto:emmachenyao@gmail.com"}
  - {title: Github, icon: github, url: "https://github.com/ychen-98"} 

# external:                  # shows a footer with social links - for available icons see fontawesome.com/icons


comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
